### ISSUE TITLE
Cmder runner

### ISSUE THREAD

**Issue by WojciechNagorski** [GrzegorzKozub/VisualStudioExtensions#3]
Do you have plan support Cmder? 
It is really great console like ConEmu.

**Comment by GrzegorzKozub** [comment]
No such plans now, but Cmder's core actually is ConEmu. 

If I remember correctly, Cmder's executable launches ConEmu but I'm not sure if the parameters passed to the former are then passed to the latter. If so, pointing to Cmder's exe in ConEmu Launcher extension options in Visual Studio should work. Give it a try and let me know, please.

One thing that could sway you towards using ConEmu over Cmder is that the brilliant author updates ConEmu very frequently while Cmder keeps a slower pace regarding this. If you like colors, like me, there's also this: https://github.com/joonro/ConEmu-Color-Themes.

**Comment by GrzegorzKozub** [comment]
Coming back to this issue I just tested and can confirm that this extension *cannot* launch Cmder due to a different command line parameters implemented by `cmder.exe` and `conemu.exe`. 

Not planning on adding Cmder support to this extension. As of today I'm also not really planning on creating a separate launcher for Cmder since the market is already a little saturated in this area.

I can suggest using this, a more general, [Open Command Line](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.OpenCommandLine) that has a good support for Cmder... and ConEmu for that matter :D

**Comment by WojciechNagorski** [comment]
Thanks!
